
name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven # ポイント1
    - name: Build and Run Tests with Maven
      run: mvn clean package # Unitテストを実行してくれる
    - name: Build with Maven
      run: mvn -B package --file pom.xml # Mavenを使ってプロジェクトをビルド

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging

  actions-timeline:
    needs: [build_test, publish-job]
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2 # ポイント2